### ISSUE TITLE
Problem with validates_uniqueness_of and validates_length_of on the same field 

### ISSUE THREAD

**Issue by FloWi** [grimen/validatious-on-rails#12] opened 2009-10-21 12:35 UTC
When I add these two validations to a field, the error for an invalid length gets displayed immediatelly. Just after that, the app validates the uniqueness (via a roundtrip to the server) and if the validation passes, the error for the length-validation disappears.

<code>validates_uniqueness_of :name
  validates_length_of :name, :within => 3..20</code>

**Comment by grimen** [comment] 2009-10-21 15:20
OK, obscure but I recognize this from my earlier problems of getting remote valdiations o work with validatious...I got it working with my scenario wth presence + format + uniqueness, but it seems this need to be re-visited.

**Comment by grimen** [comment] 2009-10-22 02:25
Sorry, can't reproduce this. Works for me - tried exactly that ^. Could you throw together a dummie-app that illustrates this?

**Comment by grimen** [comment] 2009-10-22 21:54
OK, after running your test-app I now know what you mean. I didn't see this behaviour before, I need to get to the bottom with this - no quick fix from the top of my head. I got a clue what it is, but need to debug this more.

**Comment by grimen** [comment] 2009-10-23 03:33
Peep the latest version (0.4.4). You need to generate the updated v2.Rails.js to see any difference. It's still not 100% perfect, but worked alright for me. Let me know how it works.

**Comment by FloWi** [comment] 2009-10-23 09:36
Unfortunately it doesn't fix this problem. Did you try it with my test-app and it worked? Let me know, if you make any progress and if I may try out a new version for you.

**Comment by grimen** [comment] 2009-10-23 13:45
Yes, your test-app works for me. It's just the annoying error-message-flash on a valid form submit, but that is more of annoying issue than a error.

**Comment by rajington** [comment] 2009-10-29 06:52
I also have this problem, a single field with validates_uniqueness_of. Even when entering a unique value, it flickers "has already been taken" when I leave it. From then on it works fine, I can go back to the field and leave it again without triggering another flicker. The only way to reset it to cause flickering again is by refreshing the page. Tell me if you'd like to see code. Great gem btw.

**Comment by grimen** [comment] 2009-10-29 11:34
Ye, but that is another issue: See issue #13.

**Comment by grimen** [comment] 2009-10-29 11:43
Note: I know why this happens, but more about that in issue #13.

**Comment by grimen** [comment] 2009-10-31 03:03
Except for the submit issue (already issued), I can't reproduce this error, and no new info. Closing.

**Closed as completed by grimen** 2009-10-31 03:03 UTC
Labels: can't reproduce, ajax
