### ISSUE TITLE
undefined method `reflect_on_validations_for'

### ISSUE THREAD

**Issue by lapluviosilla** [grimen/validatious-on-rails#9] opened 2009-10-16 22:29 UTC
I use authlogic for authentication and my account_session model extends Authlogic::Session::Base instead of ActiveRecord::Base. Looks like if the model doesn't extend ActiveRecord::Base then validation_reflection doesn't get added to the model which causes validatious-on-rails to break. I'm pretty sure Authlogic extends ActiveRecord::Base internally though. This might belong in the validation_reflection issue form instead.

Login form:
    - semantic_form_for @account_session, :url => account_session_path do |f|
      = f.inputs :login, :password
      = f.buttons

Stack trace:

<pre>
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/model_validations.rb:73:in `from_active_record'
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/model_validations.rb:43:in `options_for'
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/helpers.rb:5:in `attach_validator_for'
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/rails/action_view_helpers.rb:21:in `text_field_with_validation'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:944:in `text_field'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:944:in `send'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:944:in `text_field'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:497:in `send'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:497:in `input_simple'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:946:in `inline_input_for'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:108:in `send'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:108:in `input'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:107:in `map'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:107:in `input'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:256:in `inputs'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:256:in `map'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:256:in `inputs'
/Users/paul/Documents/Projects/msvngit/rails/app/views/account_sessions/new.html.haml:3:in `_run_haml_app47views47account_sessions47new46html46haml'
/Users/paul/Documents/Projects/msvngit/rails/app/views/account_sessions/new.html.haml:2:in `_run_haml_app47views47account_sessions47new46html46haml'
</pre>

**Comment by grimen** [comment] 2009-10-16 22:55
Uhm, yes I ActiveRecord::Base is required. Not sure how much effort it takes to get it to work with Authlogic::Session::Base. It's not a big priority right now - will accept patches though.

**Comment by lapluviosilla** [comment] 2009-10-19 18:50
Again, just like with the constant bug, this scenario doesn't have to be supported, but it breaks the app. The problem is that even though I set "client_side_validations_by_default" to false, validatious-on-rails still tries to analyze the validations for every formtastic form there is, including forms I don't want to validate or forms that are for an unsupported object.

The only way around this is to add another check just like you did with the constant bug. Don't know your code too well, but it looks like this check could be added right after the constantize rescue you added.

**Comment by grimen** [comment] 2009-10-21 21:34
Could you please try this?

http://github.com/grimen/validatious-on-rails/commit/d539edd5d681239473612e9ea34d5074f2e51aac

...or if you got a test app for this issue.

**Comment by grimen** [comment] 2009-10-21 21:35
..or a failing test of course.

**Comment by lapluviosilla** [comment] 2009-10-22 16:44
No, sorry this didn't work. I'm going to try and add searchlogic to my fork of test_app and add a basic search form.

**Comment by lapluviosilla** [comment] 2009-10-22 17:02
Ok, I just added a searchlogic form to my fork of the test_app and I was able to reproduce the bug. I also installed validatious-on-rails as a plugin so that it would have your latest changes. I've pushed it to github and you should be able to pull now.

**Comment by grimen** [comment] 2009-10-22 17:23
Thanks, will look into it.

**Comment by grimen** [comment] 2009-10-22 23:21
I had a bug in that fix - actually a nasty one - but now it all works as intended. The Searchlogic-form in your test-app no longer crash. =) Closing.

**Closed as completed by grimen** 2009-10-22 23:21 UTC
Labels: non-active_record, review
